server:
  port: 8083
eureka:  instance:    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:    gateway:      routes:      - id: user-service
        uri: http://localhost:8080/
        predicates:        -  Path= /home/**            